### ISSUE TITLE
Dealing with HL7 files that start with a vertical tab

### ISSUE THREAD

**Issue by newcreature517** [RobHolme/HL7-Powershell-Module#10]
I am on a project where there will be millions of HL7 messages to parse. The HL7 module works great except when trying to parse the MSH because it has a vertical tab as the first character in the file. I tried to pass `vMSH in the -ItemPosition parameter, but got the following...

> Select-HL7Item : MSH-11 does not appear to be a valid HL7 item possition
> At line:1 char:9
> + $msh =  Select-HL7Item -path "F:\Cerner Source Files\Documents\Sample ...
> +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidArgument: (MSH-11:String) [Select-HL7Item], ArgumentException
>     + FullyQualifiedErrorId : InvalidElement,HL7Tools.SelectHL7Item
> 

As I am parsing out quite a few objects out of each file, is there a way to simply read the entire file's contents into a variable, strip off the vertical tab, and then pass this string parse the string with the HL7 module? This would save opening and closing the file 15-20 times per file.

**Comment by RobHolme** [comment]
Should be trivial to remove the vertical tab characters from the file before you parse them. I assume something like:
``` powershell
(Get-Content -Path c:\temp\test.hl7).Replace("`v","") | Out-File -Path C:\temp\test.hl7 
```

Or even better, find out why the vertical tab is added to the file in the first place and fix the root issue. The vertical tab is part of the MLLP frame, but any MLLP framing is typically removed before saving the message to a file.

**Comment by newcreature517** [comment]
Rob, 
Thanks for the quick answer. Unfortunately, the files come from the vendor with the `v on them, and removing it from all the files before processing is doable, but isn't the best solution. I need to get a few dozen values out of each file and then write them to a database, so opening each HL7 message a few dozen times (some of which are several MB) multiplied by about 20 million would be pretty inefficient. 

Ideally, if your cmdlet would have a -text option that would allow it to read the text from a variable already in memory (which is where I would strip the `v), the file access would only have to happen once for each message, saving tons of I/O.

**Comment by RobHolme** [comment]
You can retrieve more than 1 value from a single query, this would remove the need to open each file multiple times.  e.g.
``` powershell
> Select-HL7Item -ItemPosition MSH-9.2, PID-3[1].1, PID-5, PID-7, PV1-2 -Path .\test.hl7

MSH-9.2    : A01
PID-3[1].1 : 10006579
PID-5      : DUCK^DONALD^D
PID-7      : 19241010
PV1-2      : I
Filename   : C:\scratch\test.hl7
```

If you need to do further processing via a script, save the result object to a variable and access the values via the variable's properties. e.g. 
``` powershell
> $results = Select-HL7Item -ItemPosition MSH-9.2, PID-3[1].1, PID-5, PID-7, PV1-2 -Path .\test.hl7

> $results.'MSH-9.2'
A01

> $results.'PID-5'
DUCK^DONALD^D
```

Reading the message contents from a file into a variable, then passing this in as a parameter will still require just as many file reads as the example above.
