### ISSUE TITLE
Consider publishing on PSGallery

### ISSUE THREAD

**Issue by Steve-Fry** [RobHolme/HL7-Powershell-Module#3]
Hi Rob, 

Awesome tool! 

Would you consider publishing the module to PSGallery in future?

**Comment by RobHolme** [comment]
Thanks. I didn't think anyone would find this useful, I'll take a look at publishing to the PSGallery.

**Comment by Toolazy2work** [comment]
Steve is right.  This is an amazing toolset.

**Comment by RobHolme** [comment]
Should be available via PSGallery now.

Install-Module -Name hl7tools

**Comment by Steve-Fry** [comment]
Oustanding! 

I have used your VSCode extension for some time too, loving your work

Thanks @RobHolme

**Comment by Toolazy2work** [comment]
@Steve-Fry I didnt even know that existed!  and now im a user as well!  thanks @RobHolme
