### ISSUE TITLE
Why this filter does not work ?

### ISSUE THREAD

**Issue by marcswm** [RobHolme/HL7-Powershell-Module#4]
Hi,

With this PV1 segment :
`PV1||O|7601^^^XX&950110999&FINEJ^^^^^^^AA|R|||0668^^^^^^^^BB^^^^EI^ETAB&950110999&FINEJ~951105212^^^^^^^^BB^^^^ADELI^ETAB&950110999&FINEJ~10000573096^^^^^^^^BB^^^^RPPS^ETAB&950110999&FINEJ|||165||||||N|||123456789^^^BB^^ETAB&950110999&FINEJ|01|10|N|||||||||||||||||||N|||20210523140300||||||456789^^^BB^^ETAB&950110999&FINEJ
`
I want to extract the PV1-7.1 field value if the PV1-7.13 is equal to ADELI, then RPPS and at last EI.
If I write 
`Select-HL7Item -Path myHL7file.hl7 -ItemPosition PV1-7.1 -filter PV1-7.13=ADELI`
I get all the PV1-7.1 values, ignoring the PV1-7.13 filter.
I tested with a dummy PV1-7.13 value : I get nothing. So the filter is used.

So what's wrong ?

Thx !

**Comment by RobHolme** [comment]
Hi,

If the filter condition involves a repeating field, then it will be evaluated against all repeats. It deems the match successful if any one of the repeating field values match the filter condition. Sorry, the documentation doesn't really mention this.

If you only wanted to evaluate one of the repeating fields in the filter, then you can use something like the following:
`-filter PV1-7[2].13=ADELI`
This will only look for a match in the second repeating element of PV1-7.13 

The same applies for the ItemPosition parameter. If it is a repeating field, all repeats are returned in an array. If you only wanted to return the second element, then use something like the following:
`-ItemPosition PV1-7[2].1`


Combining the two would return the second repeat of PV1-7.1 if the second repeat of  PV1-7.13 matches 'ADELI'
```
PS> Select-HL7Item -Path .\test.hl7 -ItemPosition PV1-7[2].1 -filter PV1-7[2].13=ADELI

ItemValue Filename
--------- --------
951105212 C:\scratch\test.hl7
```

This would only benefit you if the order of the PV1-7 repeats followed a known convention (I acknowledge this is not usually the case, or may not be safe to assume this always applies even if the order appears to have significance). 

At the moment it's not possible to search all repeats of a field for a match, then return the corresponding repeat of the field identified in the ItemPosition parameter. This would be tricky to implement, as the filter condition may evaluate a separate field to the ItemPosition parameter.  I erred on the side of being inclusive of repeating values unless a position was nominated. 

Here are some examples identifying a specific repeating element:
`OBX[2]-3` - this is the OBX-3 field value for the second repeat of the OBX segments (for repeating segments)
`PID-3[1] `- this is the PID-3 value for first repeat of the PID-3 fields (for repeating fields)
`PID-3[1].1` - this is the PID-3.1 value for the first repeat of the PID-3 field
`ZZZ[2]-1[1]` - this is the first repeat of the ZZZ-1 field from the second repeat of the ZZZ segment

regards,
Rob.

**Comment by marcswm** [comment]
Hi,

Thanks for your reply.
Ok, I see. I have a solution, not fantastic, but efficient !

I get the number of elements of PV1-7
I make a loop up to this number and test each PV1-7.13 to determine the
nature of the ID.
Of course, it's impossible (a dream !) to have a convention for this kind
of field. Each producer adds the items without worring about the order. And
all the sub-values are not required... So...

Anyway, thanks for the job ;)

Best regards.

M.
