### ISSUE TITLE
Manage several occurrences of the same segment

### ISSUE THREAD

**Issue by marcswm** [RobHolme/HL7-Powershell-Module#6]
Hi,

I have a HL7 message with several segments OBX.
I want to loop on each of them to check the values of some fields. 

```
$numberOfOBXSegments = (Select-HL7Item file.hl7 -ItemPosition OBX)."OBX")."OBX".Count
for ( $noSegment = 0; $noSegment -lt $numberOfOBXSegments; $noSegment++) {
  $OBX_3 =  (Select-HL7Item file.hl7 -ItemPosition OBX-3)."OBX-3")."OBX-3"[ $noSegment]
 .....
}
```
However, if I have 3 segments with an OBX-3 field filled only on the second one for instance, the array returned by Select-HL7Item will contain only one value (at index 0). So, I can't know it's empty on the first and last occurence.

How can I do ?

Best regards,

**Comment by RobHolme** [comment]
I can't reproduce your issue. Using your example of 3 segments with an OBX-3 field filled only on the second segment, I get an array returned with the 3 values in order - i.e. index 0 and 2 are empty, index 1 is populated. I don't get the single value you describe e.g.

![image](https://user-images.githubusercontent.com/23287323/143674221-938cdfdb-50b9-4a76-9640-f199b259db15.png)


![image](https://user-images.githubusercontent.com/23287323/143674580-a6608988-6a20-445c-a36f-2d60c158adc4.png)

**Comment by marcswm** [comment]
I found my mistake !

I need to browse each OBX segment and check fields.

To get the value of the OBX-3.2 field in the second OBX segment, I wrote

`( Select-HL7Item -path .\A.hl7 -ItemPosition OBX-3.2)."OBX-3.2"[2]`
Instead of 
`( Select-HL7Item -path .\A.hl7 -ItemPosition OBX[2]-3.2)."OBX[2]-3.2"`

Sorry for the disturb !

**Comment by RobHolme** [comment]
Glad to hear you got it working 👍
