### ISSUE TITLE
Receive-HL7Message -NOACK

### ISSUE THREAD

**Issue by GushchinPavel** [RobHolme/HL7-Powershell-Module#9]
Hello! Can you please tell me what values the -NOACK <SwitchParameter> parameter takes in the Receive-HL7Message command?

**Comment by RobHolme** [comment]
It is a switch parameter, so no values required. Setting the parameter (without any value) will suppress ACKs from being sent. 

e.g. `Receive-HL7Message -Path C:\scratch\ -Port 5000 -NoACK -Timeout 10`

https://github.com/RobHolme/HL7-Powershell-Module#receive-hl7message
